// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhnmtU37lIbHWS-Et_vwgt-Qp5XDqVL5Q',
    appId: '1:321973950443:web:1d98235ffd6c5e650dabae',
    messagingSenderId: '321973950443',
    projectId: 'flutter-chat-app-88b67',
    authDomain: 'flutter-chat-app-88b67.firebaseapp.com',
    storageBucket: 'flutter-chat-app-88b67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8XVLg0rU3gDLQH5UjG2TCwoI6C2FCgBw',
    appId: '1:321973950443:android:1d9b091fdfc2d13d0dabae',
    messagingSenderId: '321973950443',
    projectId: 'flutter-chat-app-88b67',
    storageBucket: 'flutter-chat-app-88b67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBpUB4mgbxhEukcn19mj5s8GbtT57Zs_8',
    appId: '1:321973950443:ios:b8f4d778513aa6a70dabae',
    messagingSenderId: '321973950443',
    projectId: 'flutter-chat-app-88b67',
    storageBucket: 'flutter-chat-app-88b67.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBpUB4mgbxhEukcn19mj5s8GbtT57Zs_8',
    appId: '1:321973950443:ios:9c99215aae9843370dabae',
    messagingSenderId: '321973950443',
    projectId: 'flutter-chat-app-88b67',
    storageBucket: 'flutter-chat-app-88b67.appspot.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
